apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: sample-app4

resources:
#  - project.yaml
#  - rolebindings.yaml
  - sample-app4-deploy.yaml
  - sample-app4-service.yaml
  - sample-app4-route.yaml
